package com.java.gmall.sms.dao;

import com.java.gmall.sms.entity.SmsCategoryBounds;

public interface SmsCategoryBoundsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_category_bounds
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_category_bounds
     *
     * @mbg.generated
     */
    int insert(SmsCategoryBounds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_category_bounds
     *
     * @mbg.generated
     */
    int insertSelective(SmsCategoryBounds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_category_bounds
     *
     * @mbg.generated
     */
    SmsCategoryBounds selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_category_bounds
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsCategoryBounds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_category_bounds
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsCategoryBounds record);
}