package com.java.gmall.sms.dao;

import com.java.gmall.sms.entity.SmsCouponSpuCategoryRelation;

public interface SmsCouponSpuCategoryRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    int insert(SmsCouponSpuCategoryRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    int insertSelective(SmsCouponSpuCategoryRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    SmsCouponSpuCategoryRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsCouponSpuCategoryRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_spu_category_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsCouponSpuCategoryRelation record);
}