package com.java.gmall.sms.dao;

import com.java.gmall.sms.entity.SmsHomeSubject;

public interface SmsHomeSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    int insert(SmsHomeSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    int insertSelective(SmsHomeSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    SmsHomeSubject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsHomeSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_subject
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsHomeSubject record);
}