package com.java.gmall.sms.dao;

import com.java.gmall.sms.entity.SmsHomeAdv;

public interface SmsHomeAdvMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_adv
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_adv
     *
     * @mbg.generated
     */
    int insert(SmsHomeAdv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_adv
     *
     * @mbg.generated
     */
    int insertSelective(SmsHomeAdv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_adv
     *
     * @mbg.generated
     */
    SmsHomeAdv selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_adv
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsHomeAdv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_home_adv
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsHomeAdv record);
}