package com.java.gmall.sms.dao;

import com.java.gmall.sms.entity.SmsMemberPrice;

public interface SmsMemberPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    int insert(SmsMemberPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    int insertSelective(SmsMemberPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    SmsMemberPrice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsMemberPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_member_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsMemberPrice record);
}