package com.java.gmall.sms.dao;

import com.java.gmall.sms.entity.SmsSeckillSkuRelation;

public interface SmsSeckillSkuRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    int insert(SmsSeckillSkuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    int insertSelective(SmsSeckillSkuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    SmsSeckillSkuRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsSeckillSkuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsSeckillSkuRelation record);
}