package com.java.gmall.sms.dao;

import com.java.gmall.sms.entity.SmsSpuLadder;

public interface SmsSpuLadderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_ladder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_ladder
     *
     * @mbg.generated
     */
    int insert(SmsSpuLadder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_ladder
     *
     * @mbg.generated
     */
    int insertSelective(SmsSpuLadder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_ladder
     *
     * @mbg.generated
     */
    SmsSpuLadder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_ladder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsSpuLadder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_ladder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsSpuLadder record);
}