package com.java.gmall.sms.dao;

import com.java.gmall.sms.entity.SmsSkuBounds;

public interface SmsSkuBoundsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_bounds
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_bounds
     *
     * @mbg.generated
     */
    int insert(SmsSkuBounds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_bounds
     *
     * @mbg.generated
     */
    int insertSelective(SmsSkuBounds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_bounds
     *
     * @mbg.generated
     */
    SmsSkuBounds selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_bounds
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsSkuBounds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_bounds
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsSkuBounds record);
}