package com.java.gmall.sms.dao;

import com.java.gmall.sms.entity.SmsCustPromotion;
import com.java.gmall.sms.entity.SmsSeckillPromotion;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface SmsSeckillPromotionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_promotion
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_promotion
     *
     * @mbg.generated
     */
    int insert(SmsSeckillPromotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_promotion
     *
     * @mbg.generated
     */
    int insertSelective(SmsSeckillPromotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_promotion
     *
     * @mbg.generated
     */
    SmsSeckillPromotion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_promotion
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsSeckillPromotion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_promotion
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsSeckillPromotion record);

    List<SmsCustPromotion>  selectPromotionInfoBySKUId(Long skuId);

}