package com.java.gmall.sms.dao;

import com.java.gmall.sms.entity.SmsSeckillSkuNotice;

public interface SmsSeckillSkuNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    int insert(SmsSeckillSkuNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    int insertSelective(SmsSeckillSkuNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    SmsSeckillSkuNotice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsSeckillSkuNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_seckill_sku_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsSeckillSkuNotice record);
}