package com.java.gmall.sms.dao;

import com.java.gmall.sms.entity.SmsSpuFullReduction;

public interface SmsSpuFullReductionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_full_reduction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_full_reduction
     *
     * @mbg.generated
     */
    int insert(SmsSpuFullReduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_full_reduction
     *
     * @mbg.generated
     */
    int insertSelective(SmsSpuFullReduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_full_reduction
     *
     * @mbg.generated
     */
    SmsSpuFullReduction selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_full_reduction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsSpuFullReduction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_spu_full_reduction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsSpuFullReduction record);
}