package com.java.gmall.sms.dao;

import com.java.gmall.sms.entity.SmsSkuLadder;

public interface SmsSkuLadderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    int insert(SmsSkuLadder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    int insertSelective(SmsSkuLadder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    SmsSkuLadder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsSkuLadder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_sku_ladder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsSkuLadder record);
}