package com.java.gmall.pms.dao;

import com.java.gmall.pms.entity.Attr;

public interface AttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long attrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr
     *
     * @mbg.generated
     */
    int insert(Attr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr
     *
     * @mbg.generated
     */
    int insertSelective(Attr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr
     *
     * @mbg.generated
     */
    Attr selectByPrimaryKey(Long attrId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Attr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Attr record);
}