package com.java.gmall.pms.dao;

import com.java.gmall.pms.entity.AttrAttrgroupRelation;

public interface AttrAttrgroupRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_attrgroup_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_attrgroup_relation
     *
     * @mbg.generated
     */
    int insert(AttrAttrgroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_attrgroup_relation
     *
     * @mbg.generated
     */
    int insertSelective(AttrAttrgroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_attrgroup_relation
     *
     * @mbg.generated
     */
    AttrAttrgroupRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_attrgroup_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AttrAttrgroupRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_attr_attrgroup_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AttrAttrgroupRelation record);
}