package com.java.gmall.pms.dao;

import com.java.gmall.pms.entity.ProductAttrValue;

public interface ProductAttrValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    int insert(ProductAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    int insertSelective(ProductAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    ProductAttrValue selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product_attr_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductAttrValue record);
}