package com.java.gmall.pms.dao;

import com.java.gmall.pms.entity.SkuInfo;

public interface SkuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long skuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_info
     *
     * @mbg.generated
     */
    int insert(SkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_info
     *
     * @mbg.generated
     */
    int insertSelective(SkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_info
     *
     * @mbg.generated
     */
    SkuInfo selectByPrimaryKey(long skuId);

    SkuInfo querySkuBySkuCode(Long skuCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SkuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SkuInfo record);


}