package com.java.gmall.pms.dao;

import com.java.gmall.pms.entity.SpuComment;

public interface SpuCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int insert(SpuComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int insertSelective(SpuComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    SpuComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpuComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(SpuComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpuComment record);
}