package com.java.gmall.pms.dao;

import com.java.gmall.pms.entity.SpuInfo;

public interface SpuInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_info
     *
     * @mbg.generated
     */
    int insert(SpuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_info
     *
     * @mbg.generated
     */
    int insertSelective(SpuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_info
     *
     * @mbg.generated
     */
    SpuInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SpuInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpuInfo record);
}