package com.java.gmall.pms.dao;

import com.java.gmall.pms.entity.SpuInfoDesc;

public interface SpuInfoDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_info_desc
     *
     * @mbg.generated
     */
    int insert(SpuInfoDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_spu_info_desc
     *
     * @mbg.generated
     */
    int insertSelective(SpuInfoDesc record);
}