package com.java.gmall.sms.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_coupon_spu_relation
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SmsCouponSpuRelation {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_spu_relation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   优惠券id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_spu_relation.coupon_id
     *
     * @mbg.generated
     */
    private Long couponId;

    /**
     * Database Column Remarks:
     *   spu_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_spu_relation.spu_id
     *
     * @mbg.generated
     */
    private Long spuId;

    /**
     * Database Column Remarks:
     *   spu_name
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_spu_relation.spu_name
     *
     * @mbg.generated
     */
    private String spuName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_spu_relation.id
     *
     * @return the value of sms_coupon_spu_relation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_spu_relation.id
     *
     * @param id the value for sms_coupon_spu_relation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_spu_relation.coupon_id
     *
     * @return the value of sms_coupon_spu_relation.coupon_id
     *
     * @mbg.generated
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_spu_relation.coupon_id
     *
     * @param couponId the value for sms_coupon_spu_relation.coupon_id
     *
     * @mbg.generated
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_spu_relation.spu_id
     *
     * @return the value of sms_coupon_spu_relation.spu_id
     *
     * @mbg.generated
     */
    public Long getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_spu_relation.spu_id
     *
     * @param spuId the value for sms_coupon_spu_relation.spu_id
     *
     * @mbg.generated
     */
    public void setSpuId(Long spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_spu_relation.spu_name
     *
     * @return the value of sms_coupon_spu_relation.spu_name
     *
     * @mbg.generated
     */
    public String getSpuName() {
        return spuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_spu_relation.spu_name
     *
     * @param spuName the value for sms_coupon_spu_relation.spu_name
     *
     * @mbg.generated
     */
    public void setSpuName(String spuName) {
        this.spuName = spuName;
    }
}