package com.java.gmall.sms.entity;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_seckill_promotion
 *
 * @mbg.generated do_not_delete_during_merge
 */
@JsonIgnoreProperties(value = { "hibernateLazyInitializer", "handler" })
public class SmsCustPromotion {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_promotion.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   活动标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_seckill_promotion.title
     *
     * @mbg.generated
     */
    private String title;


}