package com.java.gmall.sms.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_coupon_spu_category_relation
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SmsCouponSpuCategoryRelation {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_spu_category_relation.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   优惠券id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_spu_category_relation.coupon_id
     *
     * @mbg.generated
     */
    private Long couponId;

    /**
     * Database Column Remarks:
     *   产品分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_spu_category_relation.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     * Database Column Remarks:
     *   产品分类名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_spu_category_relation.category_name
     *
     * @mbg.generated
     */
    private String categoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_spu_category_relation.id
     *
     * @return the value of sms_coupon_spu_category_relation.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_spu_category_relation.id
     *
     * @param id the value for sms_coupon_spu_category_relation.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_spu_category_relation.coupon_id
     *
     * @return the value of sms_coupon_spu_category_relation.coupon_id
     *
     * @mbg.generated
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_spu_category_relation.coupon_id
     *
     * @param couponId the value for sms_coupon_spu_category_relation.coupon_id
     *
     * @mbg.generated
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_spu_category_relation.category_id
     *
     * @return the value of sms_coupon_spu_category_relation.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_spu_category_relation.category_id
     *
     * @param categoryId the value for sms_coupon_spu_category_relation.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_spu_category_relation.category_name
     *
     * @return the value of sms_coupon_spu_category_relation.category_name
     *
     * @mbg.generated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_spu_category_relation.category_name
     *
     * @param categoryName the value for sms_coupon_spu_category_relation.category_name
     *
     * @mbg.generated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
}