package com.java.gmall.sms.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_spu_ladder
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SmsSpuLadder {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_spu_ladder.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   spu_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_spu_ladder.spu_id
     *
     * @mbg.generated
     */
    private Long spuId;

    /**
     * Database Column Remarks:
     *   满几件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_spu_ladder.full_count
     *
     * @mbg.generated
     */
    private Integer fullCount;

    /**
     * Database Column Remarks:
     *   打几折
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_spu_ladder.discount
     *
     * @mbg.generated
     */
    private Long discount;

    /**
     * Database Column Remarks:
     *   折后价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_spu_ladder.price
     *
     * @mbg.generated
     */
    private Long price;

    /**
     * Database Column Remarks:
     *   是否叠加其他优惠[0-不可叠加，1-可叠加]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_spu_ladder.add_other
     *
     * @mbg.generated
     */
    private Boolean addOther;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_spu_ladder.id
     *
     * @return the value of sms_spu_ladder.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_spu_ladder.id
     *
     * @param id the value for sms_spu_ladder.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_spu_ladder.spu_id
     *
     * @return the value of sms_spu_ladder.spu_id
     *
     * @mbg.generated
     */
    public Long getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_spu_ladder.spu_id
     *
     * @param spuId the value for sms_spu_ladder.spu_id
     *
     * @mbg.generated
     */
    public void setSpuId(Long spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_spu_ladder.full_count
     *
     * @return the value of sms_spu_ladder.full_count
     *
     * @mbg.generated
     */
    public Integer getFullCount() {
        return fullCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_spu_ladder.full_count
     *
     * @param fullCount the value for sms_spu_ladder.full_count
     *
     * @mbg.generated
     */
    public void setFullCount(Integer fullCount) {
        this.fullCount = fullCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_spu_ladder.discount
     *
     * @return the value of sms_spu_ladder.discount
     *
     * @mbg.generated
     */
    public Long getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_spu_ladder.discount
     *
     * @param discount the value for sms_spu_ladder.discount
     *
     * @mbg.generated
     */
    public void setDiscount(Long discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_spu_ladder.price
     *
     * @return the value of sms_spu_ladder.price
     *
     * @mbg.generated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_spu_ladder.price
     *
     * @param price the value for sms_spu_ladder.price
     *
     * @mbg.generated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_spu_ladder.add_other
     *
     * @return the value of sms_spu_ladder.add_other
     *
     * @mbg.generated
     */
    public Boolean getAddOther() {
        return addOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_spu_ladder.add_other
     *
     * @param addOther the value for sms_spu_ladder.add_other
     *
     * @mbg.generated
     */
    public void setAddOther(Boolean addOther) {
        this.addOther = addOther;
    }
}