package com.java.gmall.sms.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sms_sku_bounds
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SmsSkuBounds {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_sku_bounds.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_sku_bounds.sku_id
     *
     * @mbg.generated
     */
    private Long skuId;

    /**
     * Database Column Remarks:
     *   成长积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_sku_bounds.grow_bounds
     *
     * @mbg.generated
     */
    private Long growBounds;

    /**
     * Database Column Remarks:
     *   购物积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_sku_bounds.buy_bounds
     *
     * @mbg.generated
     */
    private Long buyBounds;

    /**
     * Database Column Remarks:
     *   优惠生效情况[1111（四个状态位，从右到左）;0 - 无优惠，成长积分是否赠送;1 - 无优惠，购物积分是否赠送;2 - 有优惠，成长积分是否赠送;3 - 有优惠，购物积分是否赠送【状态位0：不赠送，1：赠送】]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_sku_bounds.work
     *
     * @mbg.generated
     */
    private Boolean work;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_sku_bounds.id
     *
     * @return the value of sms_sku_bounds.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_sku_bounds.id
     *
     * @param id the value for sms_sku_bounds.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_sku_bounds.sku_id
     *
     * @return the value of sms_sku_bounds.sku_id
     *
     * @mbg.generated
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_sku_bounds.sku_id
     *
     * @param skuId the value for sms_sku_bounds.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_sku_bounds.grow_bounds
     *
     * @return the value of sms_sku_bounds.grow_bounds
     *
     * @mbg.generated
     */
    public Long getGrowBounds() {
        return growBounds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_sku_bounds.grow_bounds
     *
     * @param growBounds the value for sms_sku_bounds.grow_bounds
     *
     * @mbg.generated
     */
    public void setGrowBounds(Long growBounds) {
        this.growBounds = growBounds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_sku_bounds.buy_bounds
     *
     * @return the value of sms_sku_bounds.buy_bounds
     *
     * @mbg.generated
     */
    public Long getBuyBounds() {
        return buyBounds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_sku_bounds.buy_bounds
     *
     * @param buyBounds the value for sms_sku_bounds.buy_bounds
     *
     * @mbg.generated
     */
    public void setBuyBounds(Long buyBounds) {
        this.buyBounds = buyBounds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_sku_bounds.work
     *
     * @return the value of sms_sku_bounds.work
     *
     * @mbg.generated
     */
    public Boolean getWork() {
        return work;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_sku_bounds.work
     *
     * @param work the value for sms_sku_bounds.work
     *
     * @mbg.generated
     */
    public void setWork(Boolean work) {
        this.work = work;
    }
}