package com.java.gmall.pms.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_comment_replay
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class CommentReplay {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment_replay.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   评论id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment_replay.comment_id
     *
     * @mbg.generated
     */
    private Long commentId;

    /**
     * Database Column Remarks:
     *   回复id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_comment_replay.reply_id
     *
     * @mbg.generated
     */
    private Long replyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment_replay.id
     *
     * @return the value of pms_comment_replay.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment_replay.id
     *
     * @param id the value for pms_comment_replay.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment_replay.comment_id
     *
     * @return the value of pms_comment_replay.comment_id
     *
     * @mbg.generated
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment_replay.comment_id
     *
     * @param commentId the value for pms_comment_replay.comment_id
     *
     * @mbg.generated
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_comment_replay.reply_id
     *
     * @return the value of pms_comment_replay.reply_id
     *
     * @mbg.generated
     */
    public Long getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_comment_replay.reply_id
     *
     * @param replyId the value for pms_comment_replay.reply_id
     *
     * @mbg.generated
     */
    public void setReplyId(Long replyId) {
        this.replyId = replyId;
    }
}