package com.java.gmall.pms.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_sku_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SkuInfo {
    /**
     * Database Column Remarks:
     *   skuId
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.sku_id
     *
     * @mbg.generated
     */
    private Long skuId;

    /**
     * Database Column Remarks:
     *   spuId
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.spu_id
     *
     * @mbg.generated
     */
    private Long spuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.sku_code
     *
     * @mbg.generated
     */
    private String skuCode;

    /**
     * Database Column Remarks:
     *   sku名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.sku_name
     *
     * @mbg.generated
     */
    private String skuName;

    /**
     * Database Column Remarks:
     *   sku介绍描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.sku_desc
     *
     * @mbg.generated
     */
    private String skuDesc;

    /**
     * Database Column Remarks:
     *   所属分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.catalog_id
     *
     * @mbg.generated
     */
    private Long catalogId;

    /**
     * Database Column Remarks:
     *   品牌id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.brand_id
     *
     * @mbg.generated
     */
    private Long brandId;

    /**
     * Database Column Remarks:
     *   默认图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.sku_default_img
     *
     * @mbg.generated
     */
    private String skuDefaultImg;

    /**
     * Database Column Remarks:
     *   标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.sku_title
     *
     * @mbg.generated
     */
    private String skuTitle;

    /**
     * Database Column Remarks:
     *   副标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.sku_subtitle
     *
     * @mbg.generated
     */
    private String skuSubtitle;

    /**
     * Database Column Remarks:
     *   价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.price
     *
     * @mbg.generated
     */
    private Long price;

    /**
     * Database Column Remarks:
     *   重量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_info.weight
     *
     * @mbg.generated
     */
    private Long weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.sku_id
     *
     * @return the value of pms_sku_info.sku_id
     *
     * @mbg.generated
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.sku_id
     *
     * @param skuId the value for pms_sku_info.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.spu_id
     *
     * @return the value of pms_sku_info.spu_id
     *
     * @mbg.generated
     */
    public Long getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.spu_id
     *
     * @param spuId the value for pms_sku_info.spu_id
     *
     * @mbg.generated
     */
    public void setSpuId(Long spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.sku_code
     *
     * @return the value of pms_sku_info.sku_code
     *
     * @mbg.generated
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.sku_code
     *
     * @param skuCode the value for pms_sku_info.sku_code
     *
     * @mbg.generated
     */
    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.sku_name
     *
     * @return the value of pms_sku_info.sku_name
     *
     * @mbg.generated
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.sku_name
     *
     * @param skuName the value for pms_sku_info.sku_name
     *
     * @mbg.generated
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.sku_desc
     *
     * @return the value of pms_sku_info.sku_desc
     *
     * @mbg.generated
     */
    public String getSkuDesc() {
        return skuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.sku_desc
     *
     * @param skuDesc the value for pms_sku_info.sku_desc
     *
     * @mbg.generated
     */
    public void setSkuDesc(String skuDesc) {
        this.skuDesc = skuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.catalog_id
     *
     * @return the value of pms_sku_info.catalog_id
     *
     * @mbg.generated
     */
    public Long getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.catalog_id
     *
     * @param catalogId the value for pms_sku_info.catalog_id
     *
     * @mbg.generated
     */
    public void setCatalogId(Long catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.brand_id
     *
     * @return the value of pms_sku_info.brand_id
     *
     * @mbg.generated
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.brand_id
     *
     * @param brandId the value for pms_sku_info.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.sku_default_img
     *
     * @return the value of pms_sku_info.sku_default_img
     *
     * @mbg.generated
     */
    public String getSkuDefaultImg() {
        return skuDefaultImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.sku_default_img
     *
     * @param skuDefaultImg the value for pms_sku_info.sku_default_img
     *
     * @mbg.generated
     */
    public void setSkuDefaultImg(String skuDefaultImg) {
        this.skuDefaultImg = skuDefaultImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.sku_title
     *
     * @return the value of pms_sku_info.sku_title
     *
     * @mbg.generated
     */
    public String getSkuTitle() {
        return skuTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.sku_title
     *
     * @param skuTitle the value for pms_sku_info.sku_title
     *
     * @mbg.generated
     */
    public void setSkuTitle(String skuTitle) {
        this.skuTitle = skuTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.sku_subtitle
     *
     * @return the value of pms_sku_info.sku_subtitle
     *
     * @mbg.generated
     */
    public String getSkuSubtitle() {
        return skuSubtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.sku_subtitle
     *
     * @param skuSubtitle the value for pms_sku_info.sku_subtitle
     *
     * @mbg.generated
     */
    public void setSkuSubtitle(String skuSubtitle) {
        this.skuSubtitle = skuSubtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.price
     *
     * @return the value of pms_sku_info.price
     *
     * @mbg.generated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.price
     *
     * @param price the value for pms_sku_info.price
     *
     * @mbg.generated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_info.weight
     *
     * @return the value of pms_sku_info.weight
     *
     * @mbg.generated
     */
    public Long getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_info.weight
     *
     * @param weight the value for pms_sku_info.weight
     *
     * @mbg.generated
     */
    public void setWeight(Long weight) {
        this.weight = weight;
    }
}