package com.java.gmall.pms.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_sku_images
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SkuImages {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_images.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   sku_id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_images.sku_id
     *
     * @mbg.generated
     */
    private Long skuId;

    /**
     * Database Column Remarks:
     *   图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_images.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_images.img_sort
     *
     * @mbg.generated
     */
    private Integer imgSort;

    /**
     * Database Column Remarks:
     *   默认图[0 - 不是默认图，1 - 是默认图]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_images.default_img
     *
     * @mbg.generated
     */
    private Integer defaultImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_images.id
     *
     * @return the value of pms_sku_images.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_images.id
     *
     * @param id the value for pms_sku_images.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_images.sku_id
     *
     * @return the value of pms_sku_images.sku_id
     *
     * @mbg.generated
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_images.sku_id
     *
     * @param skuId the value for pms_sku_images.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_images.img_url
     *
     * @return the value of pms_sku_images.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_images.img_url
     *
     * @param imgUrl the value for pms_sku_images.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_images.img_sort
     *
     * @return the value of pms_sku_images.img_sort
     *
     * @mbg.generated
     */
    public Integer getImgSort() {
        return imgSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_images.img_sort
     *
     * @param imgSort the value for pms_sku_images.img_sort
     *
     * @mbg.generated
     */
    public void setImgSort(Integer imgSort) {
        this.imgSort = imgSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_images.default_img
     *
     * @return the value of pms_sku_images.default_img
     *
     * @mbg.generated
     */
    public Integer getDefaultImg() {
        return defaultImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_images.default_img
     *
     * @param defaultImg the value for pms_sku_images.default_img
     *
     * @mbg.generated
     */
    public void setDefaultImg(Integer defaultImg) {
        this.defaultImg = defaultImg;
    }
}