package com.java.gmall.pms.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_spu_info_desc
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SpuInfoDesc {
    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_spu_info_desc.spu_id
     *
     * @mbg.generated
     */
    private Long spuId;

    /**
     * Database Column Remarks:
     *   商品介绍
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_spu_info_desc.decript
     *
     * @mbg.generated
     */
    private String decript;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_spu_info_desc.spu_id
     *
     * @return the value of pms_spu_info_desc.spu_id
     *
     * @mbg.generated
     */
    public Long getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_spu_info_desc.spu_id
     *
     * @param spuId the value for pms_spu_info_desc.spu_id
     *
     * @mbg.generated
     */
    public void setSpuId(Long spuId) {
        this.spuId = spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_spu_info_desc.decript
     *
     * @return the value of pms_spu_info_desc.decript
     *
     * @mbg.generated
     */
    public String getDecript() {
        return decript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_spu_info_desc.decript
     *
     * @param decript the value for pms_spu_info_desc.decript
     *
     * @mbg.generated
     */
    public void setDecript(String decript) {
        this.decript = decript;
    }
}