package com.java.gmall.pms.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pms_spu_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SpuInfo {
    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_spu_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_spu_info.spu_name
     *
     * @mbg.generated
     */
    private String spuName;

    /**
     * Database Column Remarks:
     *   商品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_spu_info.spu_description
     *
     * @mbg.generated
     */
    private String spuDescription;

    /**
     * Database Column Remarks:
     *   所属分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_spu_info.catalog_id
     *
     * @mbg.generated
     */
    private Long catalogId;

    /**
     * Database Column Remarks:
     *   品牌id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_spu_info.brand_id
     *
     * @mbg.generated
     */
    private Long brandId;

    /**
     * Database Column Remarks:
     *   上架状态[0 - 下架，1 - 上架]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_spu_info.publish_status
     *
     * @mbg.generated
     */
    private Byte publishStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_spu_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_spu_info.uodate_time
     *
     * @mbg.generated
     */
    private Date uodateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_spu_info.id
     *
     * @return the value of pms_spu_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_spu_info.id
     *
     * @param id the value for pms_spu_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_spu_info.spu_name
     *
     * @return the value of pms_spu_info.spu_name
     *
     * @mbg.generated
     */
    public String getSpuName() {
        return spuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_spu_info.spu_name
     *
     * @param spuName the value for pms_spu_info.spu_name
     *
     * @mbg.generated
     */
    public void setSpuName(String spuName) {
        this.spuName = spuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_spu_info.spu_description
     *
     * @return the value of pms_spu_info.spu_description
     *
     * @mbg.generated
     */
    public String getSpuDescription() {
        return spuDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_spu_info.spu_description
     *
     * @param spuDescription the value for pms_spu_info.spu_description
     *
     * @mbg.generated
     */
    public void setSpuDescription(String spuDescription) {
        this.spuDescription = spuDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_spu_info.catalog_id
     *
     * @return the value of pms_spu_info.catalog_id
     *
     * @mbg.generated
     */
    public Long getCatalogId() {
        return catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_spu_info.catalog_id
     *
     * @param catalogId the value for pms_spu_info.catalog_id
     *
     * @mbg.generated
     */
    public void setCatalogId(Long catalogId) {
        this.catalogId = catalogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_spu_info.brand_id
     *
     * @return the value of pms_spu_info.brand_id
     *
     * @mbg.generated
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_spu_info.brand_id
     *
     * @param brandId the value for pms_spu_info.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_spu_info.publish_status
     *
     * @return the value of pms_spu_info.publish_status
     *
     * @mbg.generated
     */
    public Byte getPublishStatus() {
        return publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_spu_info.publish_status
     *
     * @param publishStatus the value for pms_spu_info.publish_status
     *
     * @mbg.generated
     */
    public void setPublishStatus(Byte publishStatus) {
        this.publishStatus = publishStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_spu_info.create_time
     *
     * @return the value of pms_spu_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_spu_info.create_time
     *
     * @param createTime the value for pms_spu_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_spu_info.uodate_time
     *
     * @return the value of pms_spu_info.uodate_time
     *
     * @mbg.generated
     */
    public Date getUodateTime() {
        return uodateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_spu_info.uodate_time
     *
     * @param uodateTime the value for pms_spu_info.uodate_time
     *
     * @mbg.generated
     */
    public void setUodateTime(Date uodateTime) {
        this.uodateTime = uodateTime;
    }
}